package com.example.android.softkeyboard;

public class FinalCombinationInfo {
	static public int ERROR = -1;
	
	
	
	/**
	 * 입력된 두 종성이 조합 가능한지 판단 및 결과값 반환
	 */
	static public int checkFinalComb(int firstFinal, int secondFinal){
		int result;
		result = finalCombTable[firstFinal-4200][secondFinal-4200];
		
		return result;
	}
	
	/*
	 * 종성 음소들의 조합 정보 (겹받침)
	 * 행, 열, 값 모두 종성의 Idx를 기준으로 제작
	 */
	static private int finalCombTable[][] = {
			// 0 공백(받침이 없음)
			{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
					19, 20, 21, 22, 23, 24, 25, 26, 27 },

			// 1ㄱ 1(ㄱ)->2(ㄲ) 19(ㅅ)->3(ㄳ)
			{ ERROR, 2, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, 3, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR },

			// 2ㄲ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 3ㄳ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 4ㄴ 22(ㅈ)->5(ㄵ) ㅎ(27)->6(ㄶ)
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, 5, ERROR, ERROR, ERROR,
					ERROR, 6 },

			// 5ㄵ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 6ㄶ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 7ㄷ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 8ㄹ 1(ㄱ)->9(ㄺ) 16(ㅁ)->10(ㄻ) 17(ㅂ)->11(ㄼ) 19(ㅅ)->12(ㄽ)
			// 25(ㅌ)->13(ㄾ) 26(ㅍ)->14(ㄿ) 27(ㅎ)->15(ㅀ)
			{ ERROR, 9, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, 10, 11, ERROR,
					12, ERROR, ERROR, ERROR, ERROR, ERROR, 13, 14, 15 },

			// 9 ㄺ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 10 ㄻ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 11 ㄼ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 12 ㄽ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 13 ㄾ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 14 ㄿ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 15 ㅀ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 16 ㅁ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 17 ㅂ 19(ㅅ)->18(ㅄ)
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, 18, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR },

			// 18 ㅄ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 19 ㅅ 19(ㅅ)->20(ㅆ)
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, 20, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR },

			// 20 ㅆ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 21 ㅇ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 22 ㅈ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 23 ㅊ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 24 ㅋ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 25 ㅌ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 26 ㅍ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

			// 27 ㅎ
			{ ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR, ERROR,
					ERROR, ERROR, ERROR },

	};

}
